---
type: showroom

# Set the left column width to 30%
default_width: 30
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  # CTF Dashboard - Mission tracking and leaderboard
  - name: CTF Dashboard
    url: 'https://ctfd-leaderboard.${DOMAIN}/challenges'

  # OpenShift Console
  - name: OpenShift Console
    url: 'https://console-openshift-console.${DOMAIN}'

  # Gitea - Source Code
  - name: Gitea
    url: 'https://gitea.${DOMAIN}'
